name: Despliegue Automático Safe Haven

on:
  push:
    branches:
      - main  # Se activa cada vez que subas algo a la rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias y Compilar
        run: |
          npm install
          npm run build

      - name: Subir archivos a Hostinger vía FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/  # Sube solo lo que hay en dist
          server-dir: ./public_html/
